object FormLogin: TFormLogin
  Left = 0
  Top = 0
  BorderIcons = [biSystemMenu]
  BorderStyle = bsToolWindow
  Caption = 'Login'
  ClientHeight = 522
  ClientWidth = 505
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poDesktopCenter
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    AlignWithMargins = True
    Left = 50
    Top = 100
    Width = 405
    Height = 222
    Margins.Left = 50
    Margins.Top = 100
    Margins.Right = 50
    Margins.Bottom = 200
    Align = alClient
    BevelOuter = bvNone
    Caption = '1'
    Color = clWhite
    ParentBackground = False
    TabOrder = 0
    ExplicitTop = 150
    ExplicitWidth = 400
    ExplicitHeight = 238
    object Panel2: TPanel
      AlignWithMargins = True
      Left = 0
      Top = 173
      Width = 405
      Height = 49
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alBottom
      BevelOuter = bvNone
      Color = clWhite
      ParentBackground = False
      TabOrder = 0
      ExplicitTop = 0
      ExplicitWidth = 407
      object btnLogar: TButton
        AlignWithMargins = True
        Left = 215
        Top = 5
        Width = 175
        Height = 39
        Margins.Left = 15
        Margins.Top = 5
        Margins.Right = 15
        Margins.Bottom = 5
        Align = alRight
        Caption = 'Login'
        TabOrder = 0
        ExplicitLeft = 185
      end
      object btnCadastrar: TButton
        AlignWithMargins = True
        Left = 15
        Top = 5
        Width = 175
        Height = 39
        Margins.Left = 15
        Margins.Top = 5
        Margins.Right = 15
        Margins.Bottom = 5
        Align = alLeft
        Caption = 'Cadastrar'
        TabOrder = 1
      end
    end
    object Panel3: TPanel
      AlignWithMargins = True
      Left = 0
      Top = 91
      Width = 405
      Height = 82
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alClient
      BevelOuter = bvNone
      Color = clWhite
      ParentBackground = False
      TabOrder = 1
      ExplicitTop = 64
      ExplicitWidth = 400
      ExplicitHeight = 132
      object Edit1: TEdit
        Left = 0
        Top = 36
        Width = 405
        Height = 21
        Align = alTop
        TabOrder = 0
        TextHint = 'Informe sua senha'
        ExplicitTop = 39
        ExplicitWidth = 400
      end
      object Edit2: TEdit
        AlignWithMargins = True
        Left = 0
        Top = 0
        Width = 405
        Height = 21
        Margins.Left = 0
        Margins.Top = 0
        Margins.Right = 0
        Margins.Bottom = 15
        Align = alTop
        TabOrder = 1
        TextHint = 'Informe seu usu'#225'rio'
        ExplicitTop = 8
        ExplicitWidth = 400
      end
    end
    object Panel4: TPanel
      AlignWithMargins = True
      Left = 0
      Top = 0
      Width = 405
      Height = 91
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alTop
      BevelOuter = bvNone
      Color = clWhite
      ParentBackground = False
      TabOrder = 2
      ExplicitWidth = 400
      object Label1: TLabel
        AlignWithMargins = True
        Left = 15
        Top = 15
        Width = 375
        Height = 19
        Margins.Left = 15
        Margins.Top = 15
        Margins.Right = 15
        Margins.Bottom = 0
        Align = alTop
        Alignment = taCenter
        Caption = 'SEJA BEM VINDO!'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = [fsBold]
        ParentFont = False
        ExplicitWidth = 144
      end
    end
  end
end
