object FormReagendamento: TFormReagendamento
  Left = 0
  Top = 0
  BorderIcons = [biSystemMenu]
  BorderStyle = bsSingle
  Caption = 'Reagendamento'
  ClientHeight = 357
  ClientWidth = 388
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  OnResize = FormResize
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object Panel2: TPanel
    Left = 0
    Top = 0
    Width = 388
    Height = 357
    Align = alClient
    BevelOuter = bvNone
    Color = clWhite
    ParentBackground = False
    TabOrder = 0
    ExplicitLeft = 8
    ExplicitTop = 8
    ExplicitWidth = 580
    ExplicitHeight = 322
    object Panel1: TPanel
      Left = 0
      Top = 0
      Width = 388
      Height = 57
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 10
      Align = alTop
      BevelOuter = bvNone
      Color = 7346457
      ParentBackground = False
      TabOrder = 0
      ExplicitWidth = 580
      object lblReagendamento: TLabel
        Left = 18
        Top = 16
        Width = 155
        Height = 23
        Caption = 'Reagendamento'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -19
        Font.Name = 'Tahoma'
        Font.Style = [fsBold]
        ParentFont = False
      end
    end
    object Panel4: TPanel
      Left = 0
      Top = 57
      Width = 388
      Height = 256
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 15
      Align = alClient
      BevelOuter = bvNone
      TabOrder = 1
      ExplicitTop = 51
      ExplicitWidth = 462
      ExplicitHeight = 246
      object dtDiaReagendamento: TDateTimePicker
        AlignWithMargins = True
        Left = 18
        Top = 56
        Width = 335
        Height = 41
        Margins.Left = 0
        Margins.Top = 0
        Margins.Right = 8
        Margins.Bottom = 0
        CalColors.BackColor = clBtnFace
        Date = 45766.000000000000000000
        Time = 0.809104016203491500
        Color = 14863287
        TabOrder = 0
      end
      object timePickerHoraReagendamento: TTimePicker
        Left = 18
        Top = 128
        Width = 335
        Height = 41
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Segoe UI'
        Font.Style = []
        TabOrder = 1
        Time = 45782.839669722220000000
        TimeFormat = 'hh:mm'
      end
    end
    object Panel5: TPanel
      AlignWithMargins = True
      Left = 0
      Top = 313
      Width = 388
      Height = 34
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 10
      Align = alBottom
      BevelOuter = bvNone
      TabOrder = 2
      ExplicitTop = 278
      ExplicitWidth = 580
      object pnlDireito: TPanel
        AlignWithMargins = True
        Left = 223
        Top = 0
        Width = 160
        Height = 34
        Margins.Left = 5
        Margins.Top = 0
        Margins.Right = 5
        Margins.Bottom = 0
        Align = alRight
        BevelOuter = bvNone
        Caption = 'Salvar'
        Color = 7346457
        ParentBackground = False
        TabOrder = 0
        ExplicitLeft = 213
        object btnDireito: TSpeedButton
          Left = 0
          Top = 0
          Width = 160
          Height = 34
          Align = alClient
          Caption = 'Salvar'
          Flat = True
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -19
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          OnClick = btnDireitoClick
          ExplicitLeft = -7
          ExplicitWidth = 191
          ExplicitHeight = 41
        end
      end
      object pnlEsquerdo: TPanel
        AlignWithMargins = True
        Left = 5
        Top = 0
        Width = 160
        Height = 34
        Margins.Left = 5
        Margins.Top = 0
        Margins.Right = 5
        Margins.Bottom = 0
        Align = alLeft
        BevelOuter = bvNone
        Caption = 'Salvar'
        Color = 7346457
        ParentBackground = False
        TabOrder = 1
        object btnEsquerdo: TSpeedButton
          Left = 0
          Top = 0
          Width = 160
          Height = 34
          Align = alClient
          Caption = 'Cancelar'
          Flat = True
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -19
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          ExplicitLeft = 7
          ExplicitWidth = 183
          ExplicitHeight = 41
        end
      end
    end
  end
end
